<footer>
	<ul>
		<li><strong>Email Us:</strong></li>
		<li><a href="mailto:103712191@student.swin.edu.au">Erik Fanning</a></li>
		<li><a href="mailto:103837447@student.swin.edu.au">Pantaree (Japan) Wechsathol</a></li>
		<li><a href="mailto:103964756@student.swin.edu.au">Sarah Rhee</a></li>
		<li><a href="mailto:103146350@student.swin.edu.au">Jiaxuan (Alina) Feng</a></li>
		<li><a href="mailto:104034485@student.swin.edu.au">Vani Chopra</a></li>
	</ul>
</footer>