    <meta charset="utf-8" />
    <meta name="description" content="Computing Technology Inquiry Project" />
    <meta name="keywords"    content="HTML, CSS, PHP, SQL" />
    <meta name="author" content="Erik Fanning, Vani Chopra, Jiaxuan (Alina) Feng, Pantaree (Japan) Wechsathol, Sarah Rhee"/>
    <title>Bootstrap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="images/favicon.ico">
	<link href="styles/style.css" rel="stylesheet" media="screen and (min-width:768px)"/>
	<link href="styles/style2.css" rel="stylesheet" media="screen and (max-width:768px)"/>